### PR TITLE
Add dashboard markup

### LINKED ISSUE #140: My Shows
Build the My Shows component

Design at https://drive.google.com/file/d/1CFzsCRxv9YChrKXGWt63kjgVuwEffftL/view

### PR DESCRIPTION
**Pull request by ogdenstudios**
# Issue

This issue resolves #140 #141 #142 

# Description

This PR renders components "my shows" "currently on air" and "past shows" on the dashboard. It doesn't use any props or state yet, and the styling isn't perfect, but it gets the markup in there at least. This is my first PR here and my first stab at working in React, so I hope it's workable - happy to take criticism and feedback here.

### CODE REVIEW

**Comment by seankwilliams** [comment]
Thank you @ogdenstudios! @dzimmerman902 is going to send some feedback since I told you wrong on how the components should be broken up (I think it will just be moving some code around). Appreciate you hitting the ground running on this!

**Comment by ogdenstudios** [comment]
Sounds good, I think I have a handle on how to build out components and use them, now. Do my imports and classes look right? Had to sort of hack my way through it.

**Comment by seankwilliams** [comment]
@ogdenstudios I'll let Devin speak to everything, but the one thing I know for the CSS classes is that we want to use the BEM naming convention (http://getbem.com/), so you can read up on that when you get a chance. Also, just a heads up - some design changes will be coming for the dashboard, so don't worry too much about pushing pixels around at this stage.

**Comment by ogdenstudios** [comment]
Sounds good to me. I'll wait for more feedback from Devin and refactor along the guidelines. Thanks!

**Comment by dzimmerman902** [comment]
@ogdenstudios Great job man! We can definitely talk more on Monday about the code setup. Thanks!

**Comment by ogdenstudios** [comment]
Refactored and fixed in PR #161

**Pull request closed without merging**
