### PR TITLE
Set up albums table for the View Artist page

### LINKED ISSUE #287: View Artist page - list albums
depends on #285
depends on #288

The View Artist page should have a table of albums that reference the artist. There should be a headline that says "Albums" above the table, and the table should use React Table with the following columns:
- Album Name
- Number of Tracks
- Label
- Compilation (column values should show "Yes" if the album is a compilation, and it should be blank if the album is not a compilation)
- Updated At

Clicking on a row in the albums table should take the user to the View Album page for that record.

### PR DESCRIPTION
**Pull request by seankwilliams**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Issue

This issue resolves #287 

## Description

- Add a table with an artist's albums to the View Artist page
- Create a new API endpoint that returns an artist's albums

### CODE REVIEW

**Comment by seankwilliams** [comment]
@dzimmerman902 got another PR for you to look over when you get a chance! This will hopefully be WAY easier than the Edit Artist name one =)

**Comment by dzimmerman902** [comment]
@seankwilliams Hey Sean! Everything looks good. I'm not going to worry about the redux part yet, we can make an issue for that. Also, I would like to make the table a separate component, that'll be easier to implement once we get rid of the redux. 

Overall man, looks very clean and organized!

**Comment by seankwilliams** [comment]
@dzimmerman902 okay that sounds good - I'll make the table into its own component and let you know when that's ready!

**Comment by dzimmerman902** [comment]
@seankwilliams Awesome, sounds good!

**Comment by seankwilliams** [comment]
@dzimmerman902 the albums table is its own component now!

**Comment by dzimmerman902** [comment]
@seankwilliams You da man

**Pull request merged**
