### PR TITLE
369 new show/form/validation

### LINKED ISSUE #369: Show Calendar - Front End Validation
- [ ] Update NewShow form to use the redux-form Input component
- [ ] Add validation to fields on the front end.

### PR DESCRIPTION
**Pull request by jberns**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Issue

This issue resolves #369 

## Description

This adds the redux-form styled Input component to the New Show form.

### CODE REVIEW

**Comment by dzimmerman902** [comment]
@jberns Hey Josh! Great work on the code! Some quick tweaks I'll mention here and if you could, please review the functionality to make sure I didn't mess anything up.

1. Change the export statement for the InputLabel and InputError, mostly for code cleaning.

2. DatePicker: Added date as a default state, will help with coder knowing what is being used. Reorganized the inputs, will write docs on how to implement this further. Created methods inside class to make the render jsx look cleaner. 

3. Everything looked great with new show, I tweaked the classes just to make it more simpler. I also made the form more narrow, I think it looks better from a stylistic point. Will make a Issue in regards to having a smaller modal, maybe starting looking into libraries like we did for tooltip? I appreciate making the Repeat component but I felt it would be easier just to have it inside the main component. Renamed RepeatDropdown, I believe we should use _ inside of component names. 

If you have any questions, PLEASE don't hesitate to ask. 

Thanks!

**Comment by jberns** [comment]
Thanks Devin!  I took a quick look on my phone and think it looks good. 

The thing about the repeat component is I think it is going to get larger because the custom portion isn’t set up yet and I wanted to embed the same component in the edit modal.

**Comment by dzimmerman902** [comment]
@jberns Got ya, is it ok if I go ahead and merge this pull request so we can get it into development? We can definitely make the repeat a component later on.

**Comment by jberns** [comment]
Yup go ahead and merge!

**Comment by dzimmerman902** [comment]
You da man

**Pull request merged**
