### PR TITLE
Add Tooltip Component

### LINKED ISSUE #168: Tooltip Component

### PR DESCRIPTION
**Pull request by msiadak**
## Issue

This issue resolves #168
## Description

Adds a tooltip component.  Not ready for merging yet pending Devin's changes but wanted to get this open because it's substantially complete.  Will update once the upstream work is merged.

### CODE REVIEW

**Comment by dzimmerman902** [comment]
Thanks! I'll make sure this gets merged soon

**Comment by msiadak** [comment]
To clarify -- this will need some work after you merge your latest work, especially if we're switching to react-styleguidist (I already wrote storybook stories for the component)

**Comment by dzimmerman902** [comment]
No worries! I've been hanging onto these changes for awhile so it's a lot on me to get this figured out.

**Comment by msiadak** [comment]
This is finally ready for review/merge; includes some basic react-styleguidist docs and some basic unit tests. @dzimmerman902

**Pull request merged**
