### PR TITLE
382 textarea component

### LINKED ISSUE #382: TextArea Component
## Description of Issue

Looking for a text area component that matches our style.

## Possible Solution and/or Approach

**Props**
- [ ] Redux Form Props (meta, etc.)

**Features**
- [ ] Error
- [ ] Validation

## Additional Comments

Look at the original Input component for inspiration on how to build it

### PR DESCRIPTION
**Pull request by kmid5280**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Issue

This issue resolves #382 

## Description

Created a TextArea component with basic styling. Component and style were mostly borrowed from Input component. Also added new _TextArea.scss file to sass imports. Was able to test component by replacing current input in FormArtistUpdateName component with new TextArea component. Would like feedback on current progress.

### CODE REVIEW

**Comment by seankwilliams** [comment]
@kmid5280 nice job, I think this is looking good as far as functionality + UI! Can you clean up the pull request (there are some checkbox changes in here right now), then add the "Review" label to the PR? Then, Devin will probably have some feedback around the component.

**Comment by kmid5280** [comment]
@seankwilliams Ok, let me know how that looks.

**Comment by seankwilliams** [comment]
@kmid5280 Thanks! I think you need to do a git pull on the development branch, because the PR is now showing merge conflicts on the checkbox files. Also, please undo the change that adds the checkbox to the dashboard.

**Comment by kmid5280** [comment]
> 
> 
> @kmid5280 Thanks! I think you need to do a git pull on the development branch, because the PR is now showing merge conflicts on the checkbox files. Also, please undo the change that adds the checkbox to the dashboard.

@seankwilliams Yeah I was wondering if that was going to happen since the checkbox component has been changed. Are you suggesting to pull from the development branch and merge that with the current textarea branch? If so what's the best way to go about that?

**Comment by seankwilliams** [comment]
@kmid5280 I usually use `git merge remotes/origin/development`, then you'll have to resolve any merge conflicts locally before committing your merge.

**Comment by dzimmerman902** [comment]
@kmid5280 Hey Kyle, could you please explain why you have multiple commits called 'revert to development version'?

**Comment by kmid5280** [comment]
> 
> 
> @kmid5280 Hey Kyle, could you please explain why you have multiple commits called 'revert to development version'?

@dzimmerman902 I accidentally committed some files that don't belong in this branch, for instance the UserAddPage and Dashboard. Also since the checkbox component was changed, that was conflicting with what I had locally, so I had to merge and recommit. I was just trying to clean up the commits to get those files out of there are irrelevant to this issue. For future reference what would be a better way to do it?

**Comment by seankwilliams** [comment]
@kmid5280 merging this into development!

**Pull request merged**
