### PR TITLE
Refactor button

### PR DESCRIPTION
**Pull request by codytaft**
## Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

## Description

Refactored switch statements in Button component

### CODE REVIEW

**Comment by dzimmerman902** [comment]
Great work on this Cody! I would tweak a little more like how Marc did the Alert component. Take out the function complete and using square bracket object notation inside of the component.

**Comment by codytaft** [comment]
Should be good now.  I removed {...rest} accidentally so I added that back. The conflicts look to be just the removing of props and functions from the destructuring, but I'll let you confirm and handle that so as not to mess anything up.

**Comment by dzimmerman902** [comment]
Unfortunately there are some conflicts with this pull requeast

**Comment by codytaft** [comment]
Yah I didn't know if you wanted to check the conflict to make sure I didn't mess anything up. But I resolved them. Should be good to go.

**Pull request merged**
