### PR TITLE
Add 401 component

### LINKED ISSUE #132: 401 Unauthorized Component
# Guidelines

Have a short descriptive title <br>
Make sure to click the following:

- [ ] Assignees
- [x] Labels
- [ ] Milestone

# Full Details

Would like a simple component to display is a user tries to access a page they are not authorized to get too.

### PR DESCRIPTION
**Pull request by ogdenstudios**
## Issue

This issue resolves #132 

## Description

Added an `Unauthorized` component for when user tries to access something they shouldn't. It's missing the alert from Lauren's design, but that's being completed in #218 - once that alert is ready, we should be able to drop it on in there.

### CODE REVIEW

**Comment by dzimmerman902** [comment]
Great work @ogdenstudios! Let's try to think about how we can make this component more efficient.

Most likely we'll have different kinds of alerts with different colors/messages/etc. Try to create a more modular component that we can alter easier with props. 

For instance, if we pass in the props of danger, it will be red color. If we pass in the props of warning, it will be a yellow color.

Feel free to reach out if you have additional questions!

**Comment by dzimmerman902** [comment]
@ogdenstudios My bad! I read through in more detail and I see the placeholder for the Alert component. You did the right thing!

I appreciate the great notes, my apologies for skipping over them!

**Comment by dzimmerman902** [comment]
I'm going to check with the group on thoughts about doing a class or functional component for these types

**Comment by ogdenstudios** [comment]
Not a problem, you are managing a lot here. Thanks for all the work you do! Catch you next Monday, likely (although I am travelling back that day, so may miss it).

**Pull request merged**
