### PR TITLE
Christian

### PR DESCRIPTION
**Pull request by crodier1**
# Guidelines

DEVELOPMENT branch on the LEFT <br>
YOUR branch on the RIGHT

# Issue

This issue resolves #
CSS lacking

# Description

Inserted new css

### CODE REVIEW

**Comment by dzimmerman902** [comment]
Hey Christian! Great work on this assignment.

I need you to redo your request, everything is to be merged into the development branch and then I'll be able to review your code.

Thanks again!

**Comment by dzimmerman902** [comment]
Hey @crodier1! Great work so far, the only thing is this pull request deletes the PULL_REQUEST_TEMPLATE.md which was what we need. Almost there!

**Comment by seankwilliams** [comment]
@dzimmerman902 this is ready for your review! @crodier1 synched with development last night and the PR is now targeting `development`.

**Comment by dzimmerman902** [comment]
Looking good!

**Pull request merged**
